/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package AlphaTorrent.app;

import AlphaTorrent.app.InitializeHost;
import AlphaTorrent.config.dto.Common;
import AlphaTorrent.config.loader.ConfigLoader;
import AlphaTorrent.schedule.ChokeUnchoke;
import AlphaTorrent.schedule.OptimisticallyUnchoke;
import AlphaTorrent.state.Host;
import AlphaTorrent.tcp.Receiver;
import AlphaTorrent.utility.ByteArrayExt;
import AlphaTorrent.utility.ChunksUtility;
import AlphaTorrent.utility.Logger;
import com.fasterxml.jackson.databind.ObjectMapper;

public class App {
    public static void main(String[] args) throws InterruptedException {
        Common commonConfig = ConfigLoader.getCommon();
        InitializeHost.initializeHost();
        Receiver.initiate();
        ChokeUnchoke chokeUnchoke = new ChokeUnchoke(commonConfig.getUnchokingInterval(),commonConfig.getNumberOfPreferredNeighbors());
        chokeUnchoke.setDaemon(Boolean.TRUE);
        chokeUnchoke.start();
        OptimisticallyUnchoke optimisticallyUnchoke = new OptimisticallyUnchoke(commonConfig.getOptimisticUnchokingInterval());
        optimisticallyUnchoke.setDaemon(Boolean.TRUE);
        optimisticallyUnchoke.start();

//        Thread.sleep(30000);
        Simulation.simulate();
    }
}
