/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package AlphaTorrent.app;

import AlphaTorrent.app.InitializeHost;
import AlphaTorrent.config.loader.ConfigLoader;
import AlphaTorrent.state.Host;
import AlphaTorrent.tcp.Receiver;
import AlphaTorrent.utility.ByteArrayExt;
import AlphaTorrent.utility.ChunksUtility;
import AlphaTorrent.utility.Logger;

public class App {
    public static void main(String[] args) {
        System.out.println("Hello, world!");
        InitializeHost.initializeHost();
        Receiver.initiate();
        Simulation.simulate();
        Host host = InitializeHost.host;
        ChunksUtility.generateFileFromBytes(host.getChunks(), 1002);
        System.out.println(ByteArrayExt.getBit(host.getBitfield(),0));
        System.out.println(ByteArrayExt.getBit(host.getBitfield(),1));
        System.out.println(ByteArrayExt.getBit(host.getBitfield(),2));
        System.out.println(ByteArrayExt.getBit(host.getBitfield(),3));
        System.out.println(ByteArrayExt.getBit(host.getBitfield(),4));
        System.out.println(ByteArrayExt.getBit(host.getBitfield(),50));
        System.out.println(ByteArrayExt.getBit(host.getBitfield(),60));
        System.out.println(ByteArrayExt.getBit(host.getBitfield(),71));
        System.out.println(ByteArrayExt.getBit(host.getBitfield(),70));

    }
}
