/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package AlphaTorrent;

public class App {
    public static void main(String[] args) {
        System.out.println("Hello, world!");
        Logger.write("Hello");
        Logger.write("wrld");
    }
}
