/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package AlphaTorrent;

import AlphaTorrent.app.InitializeHost;
import AlphaTorrent.config.dto.PeerInfo;
import AlphaTorrent.config.loader.ConfigLoader;
import AlphaTorrent.neighbour.Neighbour;
import AlphaTorrent.state.Host;
import AlphaTorrent.utility.ByteArrayExt;
import AlphaTorrent.utility.ChunksUtility;

import java.net.InetAddress;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

public class App {
    public static void main(String[] args) {
        System.out.println("Hello, world!");
        Logger.write("Hello");
        Logger.write("wrld");
        System.out.println("Hello, world!");
        ConfigLoader.getPeerList();
        Host host = InitializeHost.initializeHost();
    }
}
